services:
  nut-exporter:
    image: hon95/prometheus-nut-exporter:1.2.1
    container_name: nut-exporter
    environment:
      - TZ=Europe/Budapest
      - HTTP_PATH=/metrics
    # ports:
    #   - "9995:9995"
    restart: unless-stopped
    networks:
      prometheus:
  
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    restart: unless-stopped
    # ports:
    #   - "9090:9090"
    networks:
      prometheus:

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      prometheus:
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    # ports:
    #   - "9093:9093"
    networks:
      prometheus:
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

volumes:
  grafana:
  alertmanager_data:

networks:
  prometheus:
    driver: bridge