elasticsearchHosts: "http://elasticsearch-master:9200"
replicas: 1
service:
  type: LoadBalancer
  loadBalancerIP: ""
  port: 5601
ingress:
  enabled: true
  hosts:
  - host: kibana.example.com
    paths:
    - /