persistence:
  enabled: true

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

     output {
      elasticsearch {
        hosts => "https://elasticsearch-master:9200"
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
    }

### For using external secrets for elasticsearch username and password, uncomment the following lines ###
# extraEnvs: 
#   - name: "ELASTICSEARCH_USERNAME"
#     valueFrom:
#       secretKeyRef:
#         name: elasticsearch-creds
#         key: username
#   - name: "ELASTICSEARCH_PASSWORD"
#     valueFrom:
#       secretKeyRef:
#         name: elasticsearch-creds
#         key: password
# secretMounts:
#   - name: "elasticsearch-master-certs"
#     secretName: "elasticsearch-master-certs"
#     path: "/usr/share/logstash/config/elasticsearch-master-certs"
# also add the following line to output: cacert => "/usr/share/logstash/config/elasticsearch-master-certs/ca.crt"