services:
  jupyter-latex:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-latex
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work