FROM jupyter/base-notebook:latest

USER root

RUN apt-get update && \
    apt-get install -y texlive-latex-base texlive-xetex texlive-fonts-recommended \
    texlive-latex-extra latexmk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install -U jupyterlab-latex && \
    jupyter lab build

USER jovyan

WORKDIR /home/jovyan/work

CMD ["start-notebook.sh", "--NotebookApp.token=''"]
