services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"