globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

# ports:
  # web:
  #   forwardedHeaders:
  #     insecure: true
  #   redirectTo:
  #     port: websecure
  #     priority: 10
#   websecure:
#     tls:
#       enabled: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [web, websecure]
    matchRule: Host(`traefik.example.com`)

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 10.10.10.205 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []

metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: monitoring