- name: Create etcd.env file
  template:
    src: ./templates/etcd.env.j2
    dest: /etc/etcd/etcd.env

- name: Create etcd.service file
  template:
    src: ./templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Create etcd data directory
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable etcd service
  ansible.builtin.systemd:
    name: etcd
    enabled: yes

- name: Start etcd service
  ansible.builtin.systemd:
    name: etcd
    state: started
