- name: Download and import MongoDB GPG key
  ansible.builtin.shell: |
    curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
    gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor

- name: Add MongoDB repository
  ansible.builtin.shell: |
    echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list

- name: Update package lists
  ansible.builtin.apt:
    update_cache: true

# - name: Install MongoDB
#   ansible.builtin.apt:
#     pkg:
#       - mongodb-org

# - name: Stop MongoDB service
#   ansible.builtin.systemd:
#     name: mongod
#     state: stopped
