- name: Prepare nodes
  hosts: servers
  become: true
  roles:
    - role: prepare-nodes

- name: Install MongoDB
  hosts: servers
  become: true
  roles:
    - role: install-mongo

- name: Configure MongoDB
  hosts: servers
  become: true
  roles:
    - role: configure-mongo

- name: Finalize replicaset
  hosts: servers
  become: true
  roles:
    - role: finalize-replicaset

- name: MongoDB exporter
  hosts: servers
  become: true
  roles:
    - role: mongo-exporter
