services:
  garage:
    image: dxflrs/garage:v2.1.0
    container_name: garaged
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./data/meta:/var/lib/garage/meta
      - ./data/data:/var/lib/garage/data

  webui:
    image: khairul169/garage-webui:latest
    ports:
      - "3909:3909"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
