services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat
    container_name: metricbeat
    user: root
    volumes:
      # - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    command: metricbeat -e -E output.elasticsearch.hosts=["elasticsearch:9200"]
    restart: always