

use admin;
db.createUser({ user: "replicaAdmin", pwd: "{{ replica_admin_password }}", roles: [ { role: "clusterAdmin", db: "admin" }, { role: "readWriteAnyDatabase", db: "admin" } ]})
db.grantRolesToUser("replicaAdmin", [{ role: "userAdminAnyDatabase", db: "admin" }])


use admin;
db.createUser({ user: "admin", pwd: "root", roles: [ { role: "root", db: "admin" } ] })
db.createUser({ user: "root", pwd: "root", roles: [ { role: "root", db: "admin" } ] })