- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    # upgrade: true

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - curl
      - wget
      - vim
      - gnupg
      - qemu-guest-agent
